# Define a dictionary for page icons corresponding to themes
PAGE_ICONS = {
    "insight_launcher": "🚀",
    "template": "🧩",
    "economic_growth_stability": "📈",
    "labour_market_dynamics": "💼",
    "consumer_behaviour_confidence": "🛒",
    "inflation_price_dynamics": "📉",
    "monetary_indicators_policy_effects": "💵",
    "financial_conditions_risk_analysis": "🔍",
    "global_trade_economic_relations": "🌍",
    "supply_chains_logistics": "🚢",
    "commodity_markets_pricing": "📦",
    "currency_exchange_movements": "💱",
    "market_trends_financial_health": "📊",
    "industry_performance_production": "🏭",
    "sustainability_green_economy": "🌱",
    "digital_economy_ecommerce": "🖥️",
    "innovation_rd_investment": "🚀",
    "urbanisation_and_smart_cities": "🌆",
    "healthcare_economics": "🏥",
    "education_and_human_capital": "📚",
    "social_impact_and_inequality": "🤝",
    "geopolitical_risks_and_global_stability": "🌐",
    "frontier_sectors": "🔮",
}
