# -------------------------------------------------------------------------------------------------
#  ---- Pylint Global Exceptions ----
# -------------------------------------------------------------------------------------------------
# pylint: disable=import-error, wrong-import-position, wrong-import-order
# pylint: disable=unused-variable, invalid-name, non-ascii-file-name

# -------------------------------------------------------------------------------------------------
# Docstring
# -------------------------------------------------------------------------------------------------
"""
Trade Dashboard Utilities

This module supports session-based trade tracking and dashboard review for structured trade setups.
Used within the Financial Insight Tools system to aggregate, manage, and export single or multi-leg
trades generated by calculator modules.

Key Features:
- Append structured trade dictionaries to the session state
- Display, edit, and manage trade records via Streamlit's data editor
- Download dashboard contents as CSV for record-keeping or import
- Provides safe reset mechanism and feedback messaging

Used in:
- 05_🛠_Trade_Structuring_and_Risk_Planning.py
- Extensions for shares, CFDs, and multi-leg strategy calculators (calculators.py)

"""

# -------------------------------------------------------------------------------------------------
# Third-party Libraries
# -------------------------------------------------------------------------------------------------
import streamlit as st
import pandas as pd

# -------------------------------------------------------------------------------------------------
# Dashboard Column Schema — Aligned with Calculator Output
# -------------------------------------------------------------------------------------------------
DASHBOARD_COLUMNS = [
    "Asset (Primary)",
    "Asset (Short Leg)",
    "Trade Type",
    "Trade Direction",
    "Long Entry Price (Planned)",
    "Short Entry Price (Planned)",
    "Stop Loss (Planned)",
    "Take Profit (Planned)",
    "Long Position Size (Units)",
    "Short Position Size (Units)",
    "Allocated Capital ($)",
    "Risk %",
    "Reward-to-Risk Ratio",
    "Spread Ratio (Long/Short)",
    "Correlation (90-day)",
    "Largest Divergence (3m)",
    "Leverage",
    "Track Via Spread (Y/N)",
    "Execution Price Override",
    "Broker Fees ($)",
    "Carry/Rollover Cost",
    "Transaction Costs ($)",
    "Capital Gains Tax (%)",
    "Dividend Yield (%)",
    "Slippage (%)",
    "Estimated Spread Cost",
    "Margin Required",
    "Notional Exposure",
    "Currency Conversion Rate",
    "Exchange Rate (if applicable)",
    "Reference Only",
    "Historical Context",
    "Average Spread Ratio",
    "Spread Volatility (Std Dev)",
    "Z-Score",
    "Support Levels",
    "Resistance Levels",
    "Drift Notes",
    "Notes"
]

# -------------------------------------------------------------------------------------------------
# Add Trade to Dashboard
# -------------------------------------------------------------------------------------------------
def add_trade_to_dashboard(trade_data_dict: dict) -> None:
    """
    Adds a structured trade record to the Streamlit session state dashboard.

    Args:
        trade_data_dict (dict): A dictionary of structured trade inputs,
        aligned with DASHBOARD_COLUMNS.

    Returns:
        None — updates `st.session_state.structured_trades` in-place.
    """
    if "structured_trades" not in st.session_state:
        st.session_state.structured_trades = []

    row = {col: trade_data_dict.get(col, "N/A") for col in DASHBOARD_COLUMNS}
    st.session_state.structured_trades.append(row)
    st.success(f"✅ Trade for {row['Asset (Primary)']} added to dashboard.")

# -------------------------------------------------------------------------------------------------
# Display Trade Dashboard
# -------------------------------------------------------------------------------------------------
def display_trade_dashboard() -> None:
    """
    Renders and manages the trade dashboard UI.

    Displays current session trades in an editable table, provides CSV download,
    and enables dashboard clearing via user interface controls.

    Returns:
        None — updates the UI and session state dynamically.
    """
    st.subheader("📊 Trade Structuring Dashboard")
    st.caption(
        "Your planned trade(s), structured using system tools. "
        "Use this panel to review, adjust, and export for broker integration or "
        "downstream AI support."
    )

    if "structured_trades" in st.session_state and st.session_state.structured_trades:
        dashboard_df = pd.DataFrame(st.session_state.structured_trades)

        dashboard_df = st.data_editor(
            dashboard_df,
            use_container_width=True,
            num_rows="dynamic",
            column_order=DASHBOARD_COLUMNS,
            key="trade_dashboard_editor"
        )
        st.session_state.structured_trades = dashboard_df.to_dict(orient="records")

        csv_dashboard = dashboard_df.to_csv(index=False).encode("utf-8")
        st.download_button(
            label="📥 Download Structured Trade Dashboard (CSV)",
            data=csv_dashboard,
            file_name="structured_trade_dashboard.csv",
            mime="text/csv",
        )

        if st.button("🗑️ Clear Trade Dashboard"):
            st.session_state.structured_trades = []
            st.success("Dashboard cleared.")
    else:
        st.info("No structured trades added yet. Use the calculators above "
                "to populate the dashboard for review.")
