# -------------------------------------------------------------------------------------------------
#  ---- Pylint Global Exceptions ----
# -------------------------------------------------------------------------------------------------
# pylint: disable=import-error, wrong-import-position, wrong-import-order
# pylint: disable=unused-variable, invalid-name, non-ascii-file-name

# -------------------------------------------------------------------------------------------------
# Docstring
# -------------------------------------------------------------------------------------------------
"""
Trade Dashboard Utilities

Session-based planning register for structured trade scenarios generated by the FIT trade
planning calculators.

The dashboard is intentionally a planning and review surface. It aggregates assumptions,
risk boundaries, estimated costs, and notes so scenarios can be reviewed, edited, exported,
and handed into downstream investigation or AI review workflows. It does not execute trades,
connect to brokers, or generate recommendations.
"""

# -------------------------------------------------------------------------------------------------
# Third-party Libraries
# -------------------------------------------------------------------------------------------------
import streamlit as st
import pandas as pd


# -------------------------------------------------------------------------------------------------
# Dashboard Column Schema — Aligned with Calculator Output
# -------------------------------------------------------------------------------------------------
DASHBOARD_COLUMNS = [
    # Status and identity
    "Planning Status",
    "Asset (Primary)",
    "Asset (Short Leg)",
    "Trade Type",
    "Trade Direction",

    # Entry and planned boundaries
    "Long Entry Price (Planned)",
    "Short Entry Price (Planned)",
    "Stop Loss (Planned)",
    "Take Profit (Planned)",
    "Break-even Price",

    # Size and exposure
    "Long Position Size (Units)",
    "Short Position Size (Units)",
    "Stake per Point",
    "Long Stake-per-Point",
    "Short Stake-per-Point",
    "Position Value ($)",
    "Allocated Capital ($)",
    "Notional Exposure",
    "Margin Required",
    "Leverage",

    # Risk and reward
    "Capital at Risk ($)",
    "Potential Reward ($)",
    "Risk %",
    "Target %",
    "Reward-to-Risk Ratio",
    "Risk (Combined)",
    "Potential Reward (Combined)",

    # Multi-leg details
    "Long Asset Type",
    "Short Asset Type",
    "Long Margin Required",
    "Short Margin Required",
    "Long Stop Loss (pts)",
    "Short Stop Loss (pts)",
    "Long Target (pts)",
    "Short Target (pts)",
    "Spread Ratio (Long/Short)",
    "Correlation (90-day)",
    "Largest Divergence (3m)",
    "Track Via Spread (Y/N)",

    # Costs and execution assumptions
    "Execution Price Override",
    "Broker Fees ($)",
    "Estimated Entry Costs ($)",
    "Estimated Exit Costs ($)",
    "Estimated Total Costs ($)",
    "Estimated Spread Cost",
    "Carry/Rollover Cost",
    "Transaction Costs ($)",
    "Slippage (%)",
    "Capital Gains Tax (%)",
    "Dividend Yield (%)",
    "Currency Conversion Rate",
    "Exchange Rate (if applicable)",

    # Context and notes
    "Reference Only",
    "Historical Context",
    "Average Spread Ratio",
    "Spread Volatility (Std Dev)",
    "Correlation",
    "Z-Score",
    "Support Levels",
    "Resistance Levels",
    "Drift Notes",
    "Notes"
]


# -------------------------------------------------------------------------------------------------
# Compatibility Helpers
# -------------------------------------------------------------------------------------------------
def _normalise_trade_data(trade_data_dict: dict) -> dict:
    """
    Normalise legacy calculator keys into the current dashboard schema.

    This preserves compatibility with older calculator outputs while keeping the dashboard
    organised around the planning-register schema.
    """
    normalised = dict(trade_data_dict)

    alias_map = {
        "Allocated Capital": "Allocated Capital ($)",
        "Broker Fees": "Broker Fees ($)",
        "Transaction Costs": "Transaction Costs ($)",
        "Capital at Risk": "Capital at Risk ($)",
        "Potential Reward": "Potential Reward ($)",
    }

    for legacy_key, current_key in alias_map.items():
        if current_key not in normalised and legacy_key in normalised:
            normalised[current_key] = normalised[legacy_key]

    if "Planning Status" not in normalised:
        normalised["Planning Status"] = "Planned"

    return normalised


# -------------------------------------------------------------------------------------------------
# Add Trade to Dashboard
# -------------------------------------------------------------------------------------------------
def add_trade_to_dashboard(trade_data_dict: dict) -> None:
    """
    Adds a structured trade planning record to the Streamlit session state dashboard.

    Args:
        trade_data_dict (dict): Structured trade planning inputs aligned with DASHBOARD_COLUMNS.

    Returns:
        None — updates `st.session_state.structured_trades` in-place.
    """
    if "structured_trades" not in st.session_state:
        st.session_state.structured_trades = []

    normalised = _normalise_trade_data(trade_data_dict)
    row = {col: normalised.get(col, "N/A") for col in DASHBOARD_COLUMNS}
    st.session_state.structured_trades.append(row)
    st.success(f"Planning scenario for {row['Asset (Primary)']} added to dashboard.")


# -------------------------------------------------------------------------------------------------
# Display Trade Dashboard
# -------------------------------------------------------------------------------------------------
def display_trade_dashboard() -> None:
    """
    Renders and manages the trade planning dashboard UI.

    Displays current session scenarios in an editable table, provides CSV download,
    and enables dashboard clearing via user interface controls.

    Returns:
        None — updates the UI and session state dynamically.
    """
    st.subheader("Trade Planning Dashboard")
    st.caption(
        "Review, adjust, and export structured planning scenarios. "
        "This dashboard records assumptions, risk boundaries, costs, and notes for review; "
        "it does not execute trades or connect to brokerage systems."
    )

    if "structured_trades" in st.session_state and st.session_state.structured_trades:
        dashboard_df = pd.DataFrame(st.session_state.structured_trades)

        # Ensure all expected columns exist, preserving any additional ad-hoc columns at the end.
        for col in DASHBOARD_COLUMNS:
            if col not in dashboard_df.columns:
                dashboard_df[col] = "N/A"
        extra_cols = [col for col in dashboard_df.columns if col not in DASHBOARD_COLUMNS]
        column_order = DASHBOARD_COLUMNS + extra_cols

        dashboard_df = st.data_editor(
            dashboard_df[column_order],
            width='stretch',
            num_rows="dynamic",
            column_order=column_order,
            key="trade_dashboard_editor"
        )
        st.session_state.structured_trades = dashboard_df.to_dict(orient="records")

        csv_dashboard = dashboard_df.to_csv(index=False).encode("utf-8")
        st.download_button(
            label="Download Trade Planning Dashboard (CSV)",
            data=csv_dashboard,
            file_name="trade_planning_dashboard.csv",
            mime="text/csv",
        )

        if st.button("🗑️ Clear Trade Planning Dashboard"):
            st.session_state.structured_trades = []
            st.success("Dashboard cleared.")
    else:
        st.info("No planning scenarios added yet. Use the calculators above to populate the dashboard for review.")
